### ISSUE TITLE
Feature Suggestion: Support for Android-x86 Distros

### ISSUE THREAD

**Issue by MainUserA** [TechUnRestricted/windiskwriter#10]
Hi, I would like to suggest adding support for creating bootable USB Installations for different Android-x86 distros Specially BlissOS distros which are actually the reason why I'm suggesting this because I'm having compatibility issues with those specific distros as they require SSE4.2 CPU instruction support which I'm also hoping you could bypass like you did with windows 11.

**Comment by TechUnRestricted** [comment]
Hello,

Thank you very much for your suggestion and for taking the time to share your thoughts with me. I appreciate your interest in expanding the capabilities of WinDiskWriter, specifically towards supporting bootable USB installations for Android-x86 distributions, including BlissOS.

I would like to clarify that WinDiskWriter is primarily designed and optimized for creating bootable drives for Windows operating systems. The specificity of its functionality is indeed suggested by its name, which emphasizes its focus on Windows ("Win") images.

Regarding the workaround for Windows 11, which involves editing the install.wim file, this approach leverages specific aspects of Windows operating system installations. Unfortunately, this method is not applicable or suitable for Android images due to the fundamental differences in their installation mechanisms and requirements.

While I understand the challenges and compatibility issues you've encountered, especially concerning SSE4.2 CPU instruction support for certain Android-x86 distros, my current scope and expertise are centered around Windows environments.

Thank you once again for reaching out and for your understanding.

**Comment by MainUserA** [comment]
> Hello, Thank you very much for your suggestion and for taking the time to share your thoughts with me. I appreciate your interest in expanding the capabilities of WinDiskWriter, specifically towards supporting bootable USB installations for Android-x86 distributions, including BlissOS. I would like to clarify that WinDiskWriter is primarily designed and optimized for creating bootable drives for Windows operating systems. The specificity of its functionality is indeed suggested by its name, which emphasizes its focus on Windows ("Win") images. Regarding the workaround for Windows 11, which involves editing the install.wim file, this approach leverages specific aspects of Windows operating system installations. Unfortunately, this method is not applicable or suitable for Android images due to the fundamental differences in their installation mechanisms and requirements. While I understand the challenges and compatibility issues you've encountered, especially concerning SSE4.2 CPU instruction support for certain Android-x86 distros, my current scope and expertise are centered around Windows environments. Thank you once again for reaching out and for your understanding.
> […](#)
> Wiadomość napisana przez MainUserA ***@***.***> w dniu 26.02.2024, o godz. 20:28: ﻿ Hi, I would like to suggest adding support for creating bootable USB Installations for different Android-x86 distros Specially BlissOS distros which is actually the reason why I'm suggesting this because I'm having compatibility issues with those specific distros as they require SSE4.2 CPU instruction support which I'm also hoping you could bypass like you did with windows 11. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Understood, thanks for replying and thanks for this tool.
