### ISSUE TITLE
Support Windows Server 2022 Image -  It did work!

### ISSUE THREAD

**Issue by dxniel7402** [TechUnRestricted/WinDiskWriter#16]
Hi @TechUnRestricted,

First of all, thank you for your incredible work on WinDiskWriter! A few years ago, I struggled massively to create a bootable USB stick and had to resort to using another Windows PC. Today, after just 10 minutes of Googling, I found your solution and it worked perfectly.

Although Windows Server 2022 isn't listed as supported in the README, I used it with a Windows Server 2022 image and it worked flawlessly. I think you should consider adding this to your list of supported Windows images and perhaps run some tests yourself to verify it.

Thanks again for this fantastic tool!

**Comment by TechUnRestricted** [comment]
Hi! I'm really happy that my software worked as expected for you!
Yes, **Windows Server** images _work fine_ with **WinDiskWriter**, since they're based on the same installer structure, as the regular images.  

Thanks for reminding me to add a notice about Windows Server support.  
I'll do it in a short time.

Have a nice day/night 🙂
