### ISSUE TITLE
The app worked fabulously well

### ISSUE THREAD

**Issue by nitin-gyany** [TechUnRestricted/WinDiskWriter#17]
It's ironical we can only write issues on Github. 

I'm here to say the app worked very well. There is an initial hiccup when Mac doesn't allow the app to execute. But after it is allowed, it works flawlessly.

It's a breeze when most other ISO writing apps are paid.

**Comment by TechUnRestricted** [comment]
Hi @nitin-gyany!
Thank you very much for your positive feedback about **WinDiskWriter**!

> There is an initial hiccup when Mac doesn't allow the app to execute

Yeah, my app isn't signed with **paid Apple Developer Certificate**, so users need to perform some little extra steps in order to run it. One day I'll sign it :)

For now, I'm rewriting the whole app from `Objective-C` to `Swift`, so the future development of new features will be faster 👍
