### ISSUE TITLE
Can't make an ISO file or format a partition of the same disk

### ISSUE THREAD

**Issue by MerluzaCuca** [TechUnRestricted/WinDiskWriter#19]
Sorry for bothering about a issue I already resolved myself so easily, but is there a way to not format a disk and choose a location on one to make another ISO? Or at least to install it on a partition of the same disk?

**Comment by TechUnRestricted** [comment]
Hi @MerluzaCuca.
At initial stage **WinDiskWriter** had this feature, but it was removed due to **how buggy Microsoft Windows installer is**.
So, in order to prevent any issues, caused by user-formatted USB drive, I decided to disable this feature.

What exactly could go wrong with an "improperly" formatted drive?
Well, installer can just say this:
![Windows-Could-Not-Prepare-the-Computer-to-Boot-topaz-denoise-sharpen](https://github.com/TechUnRestricted/WinDiskWriter/assets/83237609/404a5f8e-6670-4b94-8812-666cd6f2e282)  
Why? Because a USB drive is GPT and has a EFI partition! Weird. It is what it is.

Also, some functionality could be broken or even dangerous with user-defined USB partition scheme, like MBR Legacy Boot record.

<h2></h2>

If you really want it - there is a solution.  
1. Create a RAM-Disk using [this software](https://github.com/imothee/tmpdisk) (_~8GB should be enough_. Don't worry if your Mac has less RAM, it will take a swap from the SSD).
2. In "Debug" section of WinDiskWriter, enable "Scan All Whole Disks"
3. In WinDiskWriter select your RAM-Disk and write to it.
4. Copy your installer files from the RAM-Disk to the FAT32 USB partition.
5. PROFIT!
